
#一个引擎,一个模组
name: my_build_win32--scrds

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

jobs:
  build-srceng-win-32:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build-cstrike
      run: |
        
        git submodule init;git submodule update
        #sudo apt update;sudo apt upgrade;sudo apt-get install -f -y gdb libopenal-dev g++-multilib gcc-multilib libpng-dev libjpeg-dev libfreetype6-dev libfontconfig1-dev libcurl4-gnutls-dev libsdl2-dev zlib1g-dev libbz2-dev libedit-dev
        ./waf.bat configure -T release --prefix=./win --disable-warns --build-game=cstrike -d
        ./waf.bat install -j4
        
        cat build/config.log >./win/info.txt
        
    - uses: actions/upload-artifact@v3
      with:
        name: win32-source-scrds
        path: ./win
        if-no-files-found: error

