#一个引擎,一个模组
name: linux-build

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

jobs:
  build-srceng-linux-32:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: |
        sudo dpkg --add-architecture i386
        sudo apt update
        sudo apt upgrade
        sudo apt-get install -f -y libopenal-dev:i386 g++-multilib gcc-multilib libpng-dev:i386 libjpeg-dev:i386 libfreetype6-dev:i386 libfontconfig1-dev:i386 libcurl4-gnutls-dev:i386 libsdl2-dev:i386 zlib1g-dev:i386 libbz2-dev:i386 libedit-dev:i386
        export PKG_CONFIG_PATH=/usr/lib/i386-linux-gnu/pkgconfig
        git submodule init;git submodule update
        ./waf configure -T release --prefix=./linux --disable-warns -d
        ./waf install -j4
        cat build/config.log > ./linux/info.txt
    - uses: actions/upload-artifact@v3
      with:
        name: linux-source-engine-32
        path: ./linux
        if-no-files-found: error
